name: dev-test

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  check-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get latest release info
      id: get_release
      run: |
        latest_release=$(curl -s https://api.github.com/repos/hufrea/byedpi/releases/latest)
        echo "Latest release info: $latest_release"
        echo "::set-output name=tag::$(echo $latest_release | jq -r .tag_name)"
        echo "::set-output name=published_at::$(echo $latest_release | jq -r .published_at)"
    
    - name: Compare with last known release
      id: compare_release
      run: |
        last_known_release=$(cat .last_known_release 2>/dev/null || echo "")
        latest_release=${{ steps.get_release.outputs.published_at }}
        if [ "$latest_release" != "$last_known_release" ]; then
          echo "New release found: $latest_release"
          echo "::set-output name=new_release::true"
          echo $latest_release > .last_known_release
        else
          echo "No new release. Last known release: $last_known_release"
          echo "::set-output name=new_release::false"
        fi
    
    - name: Build if new release
      if: steps.compare_release.outputs.new_release == 'true'
      run: |
        echo "New release detected, building and pushing Docker..."
        docker build -t byedpi -f Dockerfile .
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build multi arch docker
      run: |
        docker buildx build \
          --platform linux/amd64 \
          --platform linux/arm/v7 \
          --platform linux/aarch64 \
          --platform linux/ppc64le \
          -t ${{ secrets.DOCKER_USERNAME }}/byedpi:test \
          --push .
